### ISSUE TITLE
Error deploying

### ISSUE THREAD

**Issue by knkrth** [salvobertoncini/ServerTorch#1]
Hi, I got this error message while running the server.

![screenshot from 2017-07-17 00-10-15](https://user-images.githubusercontent.com/12738581/28258164-66483224-6aed-11e7-80ff-21b0252adb96.png)

**Comment by salvatorebertoncini** [comment]
Hi!

You must use 127.0.0.1:8000/Server for GET requests. If you wanna use a
POST request for send raw JSON data, you can use something like Postman or
Curl. This is a work in progress project, in a few week I think i'll write
some code for WebApp and API.

Thanks a lot!

SB

2017-07-17 9:12 GMT+02:00 karthik <notifications@github.com>:

**Comment by knkrth** [comment]
Thank you. Looking towards the new updates.
